/**
 * Category seed data for the BlipZo Shopping Platform.
 *
 * Contains all 5 top-level categories, 16 subcategories, and attribute schemas
 * for Footwear, Phones, Laptops, Shirts, and Books subcategories.
 *
 * Used by the CDK custom resource Lambda to seed the categories table on deployment.
 */

import type { AttributeDefinition, AttributeSchema, CategoryNode } from '@blipzo/shared';

// ─── Top-Level Categories ────────────────────────────────────────────────────

export const TOP_LEVEL_CATEGORIES: Omit<CategoryNode, 'createdAt' | 'updatedAt'>[] = [
  {
    categoryId: 'cat_electronics',
    parentId: null,
    name: 'Electronics',
    slug: 'electronics',
    level: 1,
    isActive: true,
    icon: 'cpu',
  },
  {
    categoryId: 'cat_clothing',
    parentId: null,
    name: 'Clothing',
    slug: 'clothing',
    level: 1,
    isActive: true,
    icon: 'shirt',
  },
  {
    categoryId: 'cat_home_kitchen',
    parentId: null,
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    level: 1,
    isActive: true,
    icon: 'home',
  },
  {
    categoryId: 'cat_books',
    parentId: null,
    name: 'Books',
    slug: 'books',
    level: 1,
    isActive: true,
    icon: 'book',
  },
  {
    categoryId: 'cat_sports',
    parentId: null,
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    level: 1,
    isActive: true,
    icon: 'dumbbell',
  },
];

// ─── Subcategories ───────────────────────────────────────────────────────────

export const SUBCATEGORIES: Omit<CategoryNode, 'createdAt' | 'updatedAt'>[] = [
  // Electronics
  {
    categoryId: 'subcat_phones',
    parentId: 'cat_electronics',
    name: 'Phones',
    slug: 'phones',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_laptops',
    parentId: 'cat_electronics',
    name: 'Laptops',
    slug: 'laptops',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_accessories_elec',
    parentId: 'cat_electronics',
    name: 'Accessories',
    slug: 'accessories-electronics',
    level: 2,
    isActive: true,
  },
  // Clothing
  {
    categoryId: 'subcat_footwear',
    parentId: 'cat_clothing',
    name: 'Footwear',
    slug: 'footwear',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_shirts',
    parentId: 'cat_clothing',
    name: 'Shirts',
    slug: 'shirts',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_pants',
    parentId: 'cat_clothing',
    name: 'Pants',
    slug: 'pants',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_dresses',
    parentId: 'cat_clothing',
    name: 'Dresses',
    slug: 'dresses',
    level: 2,
    isActive: true,
  },
  // Home & Kitchen
  {
    categoryId: 'subcat_furniture',
    parentId: 'cat_home_kitchen',
    name: 'Furniture',
    slug: 'furniture',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_appliances',
    parentId: 'cat_home_kitchen',
    name: 'Appliances',
    slug: 'appliances',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_decor',
    parentId: 'cat_home_kitchen',
    name: 'Decor',
    slug: 'decor',
    level: 2,
    isActive: true,
  },
  // Books
  {
    categoryId: 'subcat_fiction',
    parentId: 'cat_books',
    name: 'Fiction',
    slug: 'fiction',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_nonfiction',
    parentId: 'cat_books',
    name: 'Non-Fiction',
    slug: 'non-fiction',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_academic',
    parentId: 'cat_books',
    name: 'Academic',
    slug: 'academic',
    level: 2,
    isActive: true,
  },
  // Sports & Outdoors
  {
    categoryId: 'subcat_equipment',
    parentId: 'cat_sports',
    name: 'Equipment',
    slug: 'equipment',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_clothing_sports',
    parentId: 'cat_sports',
    name: 'Clothing',
    slug: 'clothing-sports',
    level: 2,
    isActive: true,
  },
  {
    categoryId: 'subcat_accessories_sports',
    parentId: 'cat_sports',
    name: 'Accessories',
    slug: 'accessories-sports',
    level: 2,
    isActive: true,
  },
];

// ─── Attribute Schemas ───────────────────────────────────────────────────────

const FOOTWEAR_ATTRIBUTES: AttributeDefinition[] = [
  {
    fieldName: 'brand',
    displayLabel: 'Brand',
    dataType: 'text',
    required: true,
    filterable: true,
    displayPriority: 1,
  },
  {
    fieldName: 'availableSizes',
    displayLabel: 'Available Sizes',
    dataType: 'multi-select',
    required: true,
    allowedValues: [
      'IND 1',
      'IND 2',
      'IND 3',
      'IND 4',
      'IND 5',
      'IND 6',
      'IND 7',
      'IND 8',
      'IND 9',
      'IND 10',
      'IND 11',
      'IND 12',
    ],
    filterable: true,
    displayPriority: 2,
  },
  {
    fieldName: 'gender',
    displayLabel: 'Gender',
    dataType: 'single-select',
    required: true,
    allowedValues: ['Male', 'Female', 'Unisex'],
    filterable: true,
    displayPriority: 3,
  },
  {
    fieldName: 'ageGroup',
    displayLabel: 'Age Group',
    dataType: 'single-select',
    required: true,
    allowedValues: ['Adult', 'Kids'],
    filterable: true,
    displayPriority: 4,
  },
  {
    fieldName: 'availableColours',
    displayLabel: 'Available Colours',
    dataType: 'multi-select',
    required: true,
    allowedValues: null,
    filterable: true,
    displayPriority: 5,
  },
  {
    fieldName: 'material',
    displayLabel: 'Material',
    dataType: 'text',
    required: false,
    filterable: false,
    displayPriority: 6,
  },
  {
    fieldName: 'soleType',
    displayLabel: 'Sole Type',
    dataType: 'text',
    required: false,
    filterable: false,
    displayPriority: 7,
  },
];

const PHONES_ATTRIBUTES: AttributeDefinition[] = [
  {
    fieldName: 'brand',
    displayLabel: 'Brand',
    dataType: 'text',
    required: true,
    filterable: true,
    displayPriority: 1,
  },
  {
    fieldName: 'model',
    displayLabel: 'Model',
    dataType: 'text',
    required: true,
    filterable: false,
    displayPriority: 2,
  },
  {
    fieldName: 'ram',
    displayLabel: 'RAM',
    dataType: 'single-select',
    required: true,
    allowedValues: ['2 GB', '3 GB', '4 GB', '6 GB', '8 GB', '12 GB', '16 GB'],
    filterable: true,
    displayPriority: 3,
  },
  {
    fieldName: 'storage',
    displayLabel: 'Storage',
    dataType: 'single-select',
    required: true,
    allowedValues: ['16 GB', '32 GB', '64 GB', '128 GB', '256 GB', '512 GB', '1 TB'],
    filterable: true,
    displayPriority: 4,
  },
  {
    fieldName: 'displaySize',
    displayLabel: 'Display Size (inches)',
    dataType: 'number',
    required: true,
    filterable: false,
    displayPriority: 5,
  },
  {
    fieldName: 'batteryCapacity',
    displayLabel: 'Battery Capacity (mAh)',
    dataType: 'number',
    required: true,
    filterable: false,
    displayPriority: 6,
  },
  {
    fieldName: 'operatingSystem',
    displayLabel: 'Operating System',
    dataType: 'single-select',
    required: true,
    allowedValues: ['Android', 'iOS'],
    filterable: true,
    displayPriority: 7,
  },
  {
    fieldName: 'colour',
    displayLabel: 'Colour',
    dataType: 'multi-select',
    required: true,
    allowedValues: null,
    filterable: true,
    displayPriority: 8,
  },
];

const LAPTOPS_ATTRIBUTES: AttributeDefinition[] = [
  {
    fieldName: 'brand',
    displayLabel: 'Brand',
    dataType: 'text',
    required: true,
    filterable: true,
    displayPriority: 1,
  },
  {
    fieldName: 'model',
    displayLabel: 'Model',
    dataType: 'text',
    required: true,
    filterable: false,
    displayPriority: 2,
  },
  {
    fieldName: 'processor',
    displayLabel: 'Processor',
    dataType: 'text',
    required: true,
    filterable: true,
    displayPriority: 3,
  },
  {
    fieldName: 'ram',
    displayLabel: 'RAM',
    dataType: 'single-select',
    required: true,
    allowedValues: ['4 GB', '8 GB', '16 GB', '32 GB', '64 GB'],
    filterable: true,
    displayPriority: 4,
  },
  {
    fieldName: 'storageType',
    displayLabel: 'Storage Type',
    dataType: 'single-select',
    required: true,
    allowedValues: ['SSD', 'HDD', 'Hybrid'],
    filterable: true,
    displayPriority: 5,
  },
  {
    fieldName: 'storageCapacity',
    displayLabel: 'Storage Capacity',
    dataType: 'single-select',
    required: true,
    allowedValues: ['128 GB', '256 GB', '512 GB', '1 TB', '2 TB'],
    filterable: true,
    displayPriority: 6,
  },
  {
    fieldName: 'displaySize',
    displayLabel: 'Display Size (inches)',
    dataType: 'number',
    required: true,
    filterable: false,
    displayPriority: 7,
  },
  {
    fieldName: 'operatingSystem',
    displayLabel: 'Operating System',
    dataType: 'single-select',
    required: true,
    allowedValues: ['Windows', 'macOS', 'Linux', 'ChromeOS'],
    filterable: true,
    displayPriority: 8,
  },
  {
    fieldName: 'colour',
    displayLabel: 'Colour',
    dataType: 'multi-select',
    required: false,
    allowedValues: null,
    filterable: false,
    displayPriority: 9,
  },
];

const SHIRTS_ATTRIBUTES: AttributeDefinition[] = [
  {
    fieldName: 'brand',
    displayLabel: 'Brand',
    dataType: 'text',
    required: true,
    filterable: true,
    displayPriority: 1,
  },
  {
    fieldName: 'size',
    displayLabel: 'Size',
    dataType: 'multi-select',
    required: true,
    allowedValues: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    filterable: true,
    displayPriority: 2,
  },
  {
    fieldName: 'gender',
    displayLabel: 'Gender',
    dataType: 'single-select',
    required: true,
    allowedValues: ['Male', 'Female', 'Unisex'],
    filterable: true,
    displayPriority: 3,
  },
  {
    fieldName: 'fabric',
    displayLabel: 'Fabric',
    dataType: 'text',
    required: true,
    filterable: true,
    displayPriority: 4,
  },
  {
    fieldName: 'sleeveType',
    displayLabel: 'Sleeve Type',
    dataType: 'single-select',
    required: true,
    allowedValues: ['Full Sleeve', 'Half Sleeve', 'Sleeveless'],
    filterable: true,
    displayPriority: 5,
  },
  {
    fieldName: 'colour',
    displayLabel: 'Colour',
    dataType: 'multi-select',
    required: true,
    allowedValues: null,
    filterable: true,
    displayPriority: 6,
  },
  {
    fieldName: 'pattern',
    displayLabel: 'Pattern',
    dataType: 'single-select',
    required: false,
    allowedValues: ['Solid', 'Striped', 'Checked', 'Printed', 'Floral'],
    filterable: true,
    displayPriority: 7,
  },
];

const BOOKS_ATTRIBUTES: AttributeDefinition[] = [
  {
    fieldName: 'author',
    displayLabel: 'Author',
    dataType: 'text',
    required: true,
    filterable: true,
    displayPriority: 1,
  },
  {
    fieldName: 'isbn',
    displayLabel: 'ISBN',
    dataType: 'text',
    required: true,
    filterable: false,
    displayPriority: 2,
  },
  {
    fieldName: 'publisher',
    displayLabel: 'Publisher',
    dataType: 'text',
    required: true,
    filterable: true,
    displayPriority: 3,
  },
  {
    fieldName: 'language',
    displayLabel: 'Language',
    dataType: 'single-select',
    required: true,
    allowedValues: [
      'English',
      'Hindi',
      'Tamil',
      'Telugu',
      'Kannada',
      'Malayalam',
      'Bengali',
      'Marathi',
      'Gujarati',
    ],
    filterable: true,
    displayPriority: 4,
  },
  {
    fieldName: 'numberOfPages',
    displayLabel: 'Number of Pages',
    dataType: 'number',
    required: true,
    filterable: false,
    displayPriority: 5,
  },
  {
    fieldName: 'format',
    displayLabel: 'Format',
    dataType: 'single-select',
    required: true,
    allowedValues: ['Paperback', 'Hardcover'],
    filterable: true,
    displayPriority: 6,
  },
  {
    fieldName: 'edition',
    displayLabel: 'Edition',
    dataType: 'text',
    required: false,
    filterable: false,
    displayPriority: 7,
  },
];

// ─── Attribute Schemas (keyed by subcategoryId) ──────────────────────────────

export const ATTRIBUTE_SCHEMAS: Omit<AttributeSchema, 'createdAt'>[] = [
  {
    subcategoryId: 'subcat_footwear',
    schemaVersion: 1,
    attributes: FOOTWEAR_ATTRIBUTES,
  },
  {
    subcategoryId: 'subcat_phones',
    schemaVersion: 1,
    attributes: PHONES_ATTRIBUTES,
  },
  {
    subcategoryId: 'subcat_laptops',
    schemaVersion: 1,
    attributes: LAPTOPS_ATTRIBUTES,
  },
  {
    subcategoryId: 'subcat_shirts',
    schemaVersion: 1,
    attributes: SHIRTS_ATTRIBUTES,
  },
  {
    subcategoryId: 'subcat_fiction',
    schemaVersion: 1,
    attributes: BOOKS_ATTRIBUTES,
  },
  {
    subcategoryId: 'subcat_nonfiction',
    schemaVersion: 1,
    attributes: BOOKS_ATTRIBUTES,
  },
  {
    subcategoryId: 'subcat_academic',
    schemaVersion: 1,
    attributes: BOOKS_ATTRIBUTES,
  },
];

// ─── Combined Seed Data Export ───────────────────────────────────────────────

export const CATEGORY_SEED_DATA = {
  categories: TOP_LEVEL_CATEGORIES,
  subcategories: SUBCATEGORIES,
  attributeSchemas: ATTRIBUTE_SCHEMAS,
} as const;
